spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: ${DDL_AUTO:validate}
=======
      ddl-auto: ${DDL_AUTO:update}
>>>>>>> origin/1-feat-user-login

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
<<<<<<< HEAD
  secret: ${JWT_SECRET}
=======
  secret: ${JWT_SECRET:change-this-development-secret-key-32bytes}
>>>>>>> origin/1-feat-user-login
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
